import type { SiteData } from '@/types/site';
import { esc, mediaById } from './imageUtils';

const names: Record<string, string> = { line: 'LINE', instagram: 'Instagram', facebook: 'Facebook', threads: 'Threads', tiktok: 'TikTok', googleMap: 'Google Maps', ubereats: 'Uber Eats', foodpanda: 'foodpanda', orderForm: '訂購表單', reservation: '訂位' };
function asset(data: SiteData, id?: string) { const m = mediaById(data, id); return m ? `assets/${m.id}.${(m.mimeType.split('/')[1] || 'png').replace('jpeg', 'jpg')}` : ''; }
function links(data: SiteData) { return Object.entries(data.links).filter(([, v]) => v).map(([k, v]) => `<a class="btn" href="${esc(v)}" target="_blank" rel="noopener noreferrer">${esc(names[k] || k)}</a>`).join(''); }
function productCard(data: SiteData, i: SiteData['menu']['categories'][number]['items'][number]) { const img = asset(data, i.imageId); return `<article class="card">${img ? `<img class="product-img" src="${esc(img)}" alt="${esc(i.name)}">` : ''}<h3>${esc(i.name)}</h3><p class="muted">${esc(i.description)}</p><p class="price">$${esc(i.price)}</p></article>`; }

export function exportStaticSite(data: SiteData) {
  const featured = data.menu.categories.flatMap(c => c.items).filter(i => i.featured);
  const hero = asset(data, data.hero.imageId);
  const og = asset(data, data.seo.ogImageId) || hero;
  const css = `*{box-sizing:border-box}body{margin:0;font-family:${data.theme.fontFamily === 'serif' ? 'Georgia,serif' : 'system-ui,sans-serif'};background:${data.theme.backgroundColor};color:${data.theme.textColor}}.wrap{max-width:1080px;margin:auto;padding:28px}.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:28px;align-items:center}.hero img,.card{border-radius:${data.theme.sectionRadius}px}.hero img{width:100%;height:360px;object-fit:cover;background:#f1f5f9}.btn{display:inline-block;margin:6px 8px 6px 0;padding:12px 18px;border-radius:${data.theme.buttonStyle === 'square' ? 4 : data.theme.buttonStyle === 'rounded' ? 12 : 999}px;background:${data.theme.primaryColor};color:white;text-decoration:none;font-weight:800}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.card{background:white;padding:18px;box-shadow:0 8px 24px #0f172a12;margin:12px 0}.product-img{width:100%;height:160px;object-fit:cover;border-radius:14px}.muted{opacity:.72}.price{color:${data.theme.primaryColor};font-weight:900}@media(max-width:720px){.hero{grid-template-columns:1fr}.hero h1{font-size:36px}.wrap{padding:18px}}`;
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(data.seo.title || data.store.name)}</title><meta name="description" content="${esc(data.seo.description || data.store.description)}"><meta property="og:title" content="${esc(data.seo.title || data.store.name)}"><meta property="og:description" content="${esc(data.seo.description || data.store.description)}"><meta property="og:image" content="${esc(og)}"><style>${css}</style></head><body><main class="wrap">${data.modules.hero ? `<section class="hero"><div><p class="price">${esc(data.store.tagline)}</p><h1>${esc(data.hero.title)}</h1><p class="muted">${esc(data.hero.subtitle)}</p>${links(data)}</div>${hero ? `<img src="${esc(hero)}" alt="hero">` : ''}</section>` : ''}${data.modules.brandStory ? `<section class="card"><h2>品牌故事</h2><p>${esc(data.store.description)}</p></section>` : ''}${data.modules.featuredProducts ? `<h2>招牌商品</h2><div class="grid">${featured.map(i => productCard(data, i)).join('')}</div>` : ''}${data.modules.menu ? `<h2>菜單總覽</h2>${data.menu.categories.map(c => `<section class="card"><h3>${esc(c.name)}</h3>${c.items.map(i => `<p><b>${esc(i.name)}</b> <span class="price">$${esc(i.price)}</span><br><span class="muted">${esc(i.description)}</span></p>`).join('')}</section>`).join('')}` : ''}${data.modules.storeInfo ? `<section class="card"><h2>門市資訊</h2><p>📍 ${esc(data.store.address)}</p><p>☎ ${esc(data.store.phone)}</p><p>✉ ${esc(data.store.email)}</p><p>🕘 ${esc(data.store.businessHours)}</p></section>` : ''}${data.modules.socialLinks ? `<section>${links(data)}</section>` : ''}${data.modules.faq ? `<h2>FAQ</h2>${data.faq.map(f => `<details class="card"><summary>${esc(f.question)}</summary><p>${esc(f.answer)}</p></details>`).join('')}` : ''}${data.modules.footer ? `<footer class="muted" style="text-align:center;padding:32px">© ${new Date().getFullYear()} ${esc(data.store.name)}</footer>` : ''}</main></body></html>`;
}
