import type { TemplateIndustry } from '@/types/template';

export type TemplateVisualContract = {
  templateId: string;
  templateName: string;
  industry: TemplateIndustry;
  sourceArtwork: { gallerySrc: string; previewHeroSrc: string; exportHeroSrc: string; mustUseSameArtwork: boolean };
  visualIdentity: { mood: string; primaryKeywords: string[]; forbiddenLook: string[]; requiredLook: string[] };
  pageSkin: { background: string; texture: string; overallMood: string };
  headerSkin: { expectedStyle: string; background: string; textColor: string; borderOrShadow: string };
  heroSkin: { artworkUsage: 'full-bleed' | 'split' | 'poster' | 'framed' | 'editorial'; overlayRequired: boolean; textPanelRequired: boolean; headingReadable: boolean; ctaVisible: boolean };
  sectionSkin: { brandStoryStyle: string; productSectionStyle: string; menuSectionStyle: string; storeInfoStyle: string; faqStyle: string; footerStyle: string };
  productCardSkin: { cardMode: string; background: string; border: string; priceColor: string; imagePlaceholderStyle: string; mustNotBeGenericWhiteCard: boolean };
  menuListSkin: { listMode: string; rowStyle: string; priceStyle: string; mustNotBeGenericWhiteList: boolean };
  placeholderSkin: { placeholderMode: string; mustNotShowStoreSiteBuilderText: boolean; mustMatchTemplateMood: boolean };
  exportRequirement: { exportMustMatchPreview: boolean; artworkMustBeInAssets: boolean; noRemoteDependency: boolean };
};

export const templateVisualContracts = [
  {
    templateId: 'drink-matcha-hiyori',
    templateName: '抹茶日和',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-matcha-hiyori.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-matcha-hiyori.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-matcha-hiyori.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '米白、抹茶綠、柔和日系、茶葉感', primaryKeywords: ['米白', '抹茶綠', '柔和日系', '茶葉感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡或普通灰色 placeholder'], requiredLook: ['米白柔和卡', '乾淨日系清單', '茶葉抽象 placeholder'] },
    pageSkin: { background: '米白、抹茶綠、柔和日系、茶葉感', texture: '茶葉抽象 placeholder', overallMood: '米白、抹茶綠、柔和日系、茶葉感' },
    headerSkin: { expectedStyle: '米白、抹茶綠、柔和日系、茶葉感 header/nav', background: '必須呼應 抹茶日和 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 抹茶日和 mood 客製' },
    heroSkin: { artworkUsage: 'split', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '米白、抹茶綠、柔和日系、茶葉感 品牌故事', productSectionStyle: '米白柔和卡', menuSectionStyle: '乾淨日系清單', storeInfoStyle: '抹茶日和 資訊卡', faqStyle: '抹茶日和 FAQ', footerStyle: '米白、抹茶綠、柔和日系、茶葉感 footer' },
    productCardSkin: { cardMode: '米白柔和卡', background: '米白柔和卡', border: '依 抹茶日和 palette 客製邊框', priceColor: '依 抹茶日和 accent 客製', imagePlaceholderStyle: '茶葉抽象 placeholder', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '乾淨日系清單', rowStyle: '依 抹茶日和 mood 客製 row', priceStyle: '依 抹茶日和 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '茶葉抽象 placeholder', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-boba-neon',
    templateName: '珍珠霓光',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-boba-neon.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-boba-neon.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-boba-neon.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '深色霓虹、紫藍粉、高對比、潮流感', primaryKeywords: ['深色霓虹', '紫藍粉', '高對比', '潮流感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通藍底或普通白卡'], requiredLook: ['dark glass / neon border', 'dark list', '霓虹飲品抽象'] },
    pageSkin: { background: '深色霓虹、紫藍粉、高對比、潮流感', texture: '霓虹飲品抽象', overallMood: '深色霓虹、紫藍粉、高對比、潮流感' },
    headerSkin: { expectedStyle: '深色霓虹、紫藍粉、高對比、潮流感 header/nav', background: '必須呼應 珍珠霓光 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 珍珠霓光 mood 客製' },
    heroSkin: { artworkUsage: 'framed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '深色霓虹、紫藍粉、高對比、潮流感 品牌故事', productSectionStyle: 'dark glass / neon border', menuSectionStyle: 'dark list', storeInfoStyle: '珍珠霓光 資訊卡', faqStyle: '珍珠霓光 FAQ', footerStyle: '深色霓虹、紫藍粉、高對比、潮流感 footer' },
    productCardSkin: { cardMode: 'dark glass / neon border', background: 'dark glass / neon border', border: '依 珍珠霓光 palette 客製邊框', priceColor: '依 珍珠霓光 accent 客製', imagePlaceholderStyle: '霓虹飲品抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'dark list', rowStyle: '依 珍珠霓光 mood 客製 row', priceStyle: '依 珍珠霓光 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '霓虹飲品抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-fruit-paradise',
    templateName: '果香樂園',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-fruit-paradise.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-fruit-paradise.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-fruit-paradise.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '水果色、明亮、活潑、促銷', primaryKeywords: ['水果色', '明亮', '活潑', '促銷'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得只用淡綠色板'], requiredLook: ['亮色水果卡', 'playful menu', '水果色 blob'] },
    pageSkin: { background: '水果色、明亮、活潑、促銷', texture: '水果色 blob', overallMood: '水果色、明亮、活潑、促銷' },
    headerSkin: { expectedStyle: '水果色、明亮、活潑、促銷 header/nav', background: '必須呼應 果香樂園 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 果香樂園 mood 客製' },
    heroSkin: { artworkUsage: 'poster', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '水果色、明亮、活潑、促銷 品牌故事', productSectionStyle: '亮色水果卡', menuSectionStyle: 'playful menu', storeInfoStyle: '果香樂園 資訊卡', faqStyle: '果香樂園 FAQ', footerStyle: '水果色、明亮、活潑、促銷 footer' },
    productCardSkin: { cardMode: '亮色水果卡', background: '亮色水果卡', border: '依 果香樂園 palette 客製邊框', priceColor: '依 果香樂園 accent 客製', imagePlaceholderStyle: '水果色 blob', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'playful menu', rowStyle: '依 果香樂園 mood 客製 row', priceStyle: '依 果香樂園 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '水果色 blob', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-brown-sugar-amber',
    templateName: '黑糖琥珀',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-brown-sugar-amber.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-brown-sugar-amber.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-brown-sugar-amber.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '琥珀棕、奶茶、焦糖、暖色', primaryKeywords: ['琥珀棕', '奶茶', '焦糖', '暖色'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡'], requiredLook: ['奶茶棕卡，琥珀價格', '暖棕餐牌感', '奶茶/琥珀抽象'] },
    pageSkin: { background: '琥珀棕、奶茶、焦糖、暖色', texture: '奶茶/琥珀抽象', overallMood: '琥珀棕、奶茶、焦糖、暖色' },
    headerSkin: { expectedStyle: '琥珀棕、奶茶、焦糖、暖色 header/nav', background: '必須呼應 黑糖琥珀 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 黑糖琥珀 mood 客製' },
    heroSkin: { artworkUsage: 'full-bleed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '琥珀棕、奶茶、焦糖、暖色 品牌故事', productSectionStyle: '奶茶棕卡，琥珀價格', menuSectionStyle: '暖棕餐牌感', storeInfoStyle: '黑糖琥珀 資訊卡', faqStyle: '黑糖琥珀 FAQ', footerStyle: '琥珀棕、奶茶、焦糖、暖色 footer' },
    productCardSkin: { cardMode: '奶茶棕卡，琥珀價格', background: '奶茶棕卡，琥珀價格', border: '依 黑糖琥珀 palette 客製邊框', priceColor: '依 黑糖琥珀 accent 客製', imagePlaceholderStyle: '奶茶/琥珀抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '暖棕餐牌感', rowStyle: '依 黑糖琥珀 mood 客製 row', priceStyle: '依 黑糖琥珀 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '奶茶/琥珀抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-white-peach-sparkle',
    templateName: '白桃氣泡',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-white-peach-sparkle.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-white-peach-sparkle.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-white-peach-sparkle.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '粉桃、氣泡、甜美、柔和', primaryKeywords: ['粉桃', '氣泡', '甜美', '柔和'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得淡到看不見'], requiredLook: ['粉桃白卡，氣泡裝飾', '粉色價格', '桃粉氣泡'] },
    pageSkin: { background: '粉桃、氣泡、甜美、柔和', texture: '桃粉氣泡', overallMood: '粉桃、氣泡、甜美、柔和' },
    headerSkin: { expectedStyle: '粉桃、氣泡、甜美、柔和 header/nav', background: '必須呼應 白桃氣泡 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 白桃氣泡 mood 客製' },
    heroSkin: { artworkUsage: 'split', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '粉桃、氣泡、甜美、柔和 品牌故事', productSectionStyle: '粉桃白卡，氣泡裝飾', menuSectionStyle: '粉色價格', storeInfoStyle: '白桃氣泡 資訊卡', faqStyle: '白桃氣泡 FAQ', footerStyle: '粉桃、氣泡、甜美、柔和 footer' },
    productCardSkin: { cardMode: '粉桃白卡，氣泡裝飾', background: '粉桃白卡，氣泡裝飾', border: '依 白桃氣泡 palette 客製邊框', priceColor: '依 白桃氣泡 accent 客製', imagePlaceholderStyle: '桃粉氣泡', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '粉色價格', rowStyle: '依 白桃氣泡 mood 客製 row', priceStyle: '依 白桃氣泡 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '桃粉氣泡', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-lime-morning',
    templateName: '青檸清晨',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-lime-morning.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-lime-morning.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-lime-morning.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '青檸綠、清爽、健康、早晨感', primaryKeywords: ['青檸綠', '清爽', '健康', '早晨感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡'], requiredLook: ['清爽淺綠 / 白卡', '健康系清單', '檸檬/青檸抽象'] },
    pageSkin: { background: '青檸綠、清爽、健康、早晨感', texture: '檸檬/青檸抽象', overallMood: '青檸綠、清爽、健康、早晨感' },
    headerSkin: { expectedStyle: '青檸綠、清爽、健康、早晨感 header/nav', background: '必須呼應 青檸清晨 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 青檸清晨 mood 客製' },
    heroSkin: { artworkUsage: 'poster', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '青檸綠、清爽、健康、早晨感 品牌故事', productSectionStyle: '清爽淺綠 / 白卡', menuSectionStyle: '健康系清單', storeInfoStyle: '青檸清晨 資訊卡', faqStyle: '青檸清晨 FAQ', footerStyle: '青檸綠、清爽、健康、早晨感 footer' },
    productCardSkin: { cardMode: '清爽淺綠 / 白卡', background: '清爽淺綠 / 白卡', border: '依 青檸清晨 palette 客製邊框', priceColor: '依 青檸清晨 accent 客製', imagePlaceholderStyle: '檸檬/青檸抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '健康系清單', rowStyle: '依 青檸清晨 mood 客製 row', priceStyle: '依 青檸清晨 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '檸檬/青檸抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-tea-mist-ridge',
    templateName: '茶霧山嵐',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-tea-mist-ridge.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-tea-mist-ridge.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-tea-mist-ridge.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '深綠、霧感、高山茶、精品', primaryKeywords: ['深綠', '霧感', '高山茶', '精品'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得單純深綠色板'], requiredLook: ['深綠 / 米色精品茶卡', 'editorial tea menu', '茶霧 / 茶葉抽象'] },
    pageSkin: { background: '深綠、霧感、高山茶、精品', texture: '茶霧 / 茶葉抽象', overallMood: '深綠、霧感、高山茶、精品' },
    headerSkin: { expectedStyle: '深綠、霧感、高山茶、精品 header/nav', background: '必須呼應 茶霧山嵐 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 茶霧山嵐 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '深綠、霧感、高山茶、精品 品牌故事', productSectionStyle: '深綠 / 米色精品茶卡', menuSectionStyle: 'editorial tea menu', storeInfoStyle: '茶霧山嵐 資訊卡', faqStyle: '茶霧山嵐 FAQ', footerStyle: '深綠、霧感、高山茶、精品 footer' },
    productCardSkin: { cardMode: '深綠 / 米色精品茶卡', background: '深綠 / 米色精品茶卡', border: '依 茶霧山嵐 palette 客製邊框', priceColor: '依 茶霧山嵐 accent 客製', imagePlaceholderStyle: '茶霧 / 茶葉抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'editorial tea menu', rowStyle: '依 茶霧山嵐 mood 客製 row', priceStyle: '依 茶霧山嵐 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '茶霧 / 茶葉抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-iced-party',
    templateName: '星冰派對',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-iced-party.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-iced-party.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-iced-party.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '冰飲、夏季、促銷、派對', primaryKeywords: ['冰飲', '夏季', '促銷', '派對'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通淺藍卡'], requiredLook: ['亮藍 / 黃 / 橘活動卡', '促銷型菜單', '冰塊 / 派對色塊'] },
    pageSkin: { background: '冰飲、夏季、促銷、派對', texture: '冰塊 / 派對色塊', overallMood: '冰飲、夏季、促銷、派對' },
    headerSkin: { expectedStyle: '冰飲、夏季、促銷、派對 header/nav', background: '必須呼應 星冰派對 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 星冰派對 mood 客製' },
    heroSkin: { artworkUsage: 'poster', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '冰飲、夏季、促銷、派對 品牌故事', productSectionStyle: '亮藍 / 黃 / 橘活動卡', menuSectionStyle: '促銷型菜單', storeInfoStyle: '星冰派對 資訊卡', faqStyle: '星冰派對 FAQ', footerStyle: '冰飲、夏季、促銷、派對 footer' },
    productCardSkin: { cardMode: '亮藍 / 黃 / 橘活動卡', background: '亮藍 / 黃 / 橘活動卡', border: '依 星冰派對 palette 客製邊框', priceColor: '依 星冰派對 accent 客製', imagePlaceholderStyle: '冰塊 / 派對色塊', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '促銷型菜單', rowStyle: '依 星冰派對 mood 客製 row', priceStyle: '依 星冰派對 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '冰塊 / 派對色塊', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-afternoon-cream',
    templateName: '午後奶蓋',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-afternoon-cream.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-afternoon-cream.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-afternoon-cream.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '奶油色、午後、生活感、療癒', primaryKeywords: ['奶油色', '午後', '生活感', '療癒'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡'], requiredLook: ['奶油白卡，柔和陰影', '溫柔生活感', '奶蓋 / 柔和圓形'] },
    pageSkin: { background: '奶油色、午後、生活感、療癒', texture: '奶蓋 / 柔和圓形', overallMood: '奶油色、午後、生活感、療癒' },
    headerSkin: { expectedStyle: '奶油色、午後、生活感、療癒 header/nav', background: '必須呼應 午後奶蓋 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 午後奶蓋 mood 客製' },
    heroSkin: { artworkUsage: 'split', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '奶油色、午後、生活感、療癒 品牌故事', productSectionStyle: '奶油白卡，柔和陰影', menuSectionStyle: '溫柔生活感', storeInfoStyle: '午後奶蓋 資訊卡', faqStyle: '午後奶蓋 FAQ', footerStyle: '奶油色、午後、生活感、療癒 footer' },
    productCardSkin: { cardMode: '奶油白卡，柔和陰影', background: '奶油白卡，柔和陰影', border: '依 午後奶蓋 palette 客製邊框', priceColor: '依 午後奶蓋 accent 客製', imagePlaceholderStyle: '奶蓋 / 柔和圓形', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '溫柔生活感', rowStyle: '依 午後奶蓋 mood 客製 row', priceStyle: '依 午後奶蓋 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '奶蓋 / 柔和圓形', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'drink-lab-brew',
    templateName: '飲研實驗室',
    industry: 'drink-shop',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/drink-shop/drink-lab-brew.png', previewHeroSrc: '/template-gallery-ai/drink-shop/drink-lab-brew.png', exportHeroSrc: '/template-gallery-ai/drink-shop/drink-lab-brew.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '科技感、透明感、實驗室、創新', primaryKeywords: ['科技感', '透明感', '實驗室', '創新'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得一般飲料色卡'], requiredLook: ['玻璃感 / 青綠 / 冷色', '科技清單', '實驗器皿 / 氣泡抽象'] },
    pageSkin: { background: '科技感、透明感、實驗室、創新', texture: '實驗器皿 / 氣泡抽象', overallMood: '科技感、透明感、實驗室、創新' },
    headerSkin: { expectedStyle: '科技感、透明感、實驗室、創新 header/nav', background: '必須呼應 飲研實驗室 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 飲研實驗室 mood 客製' },
    heroSkin: { artworkUsage: 'framed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '科技感、透明感、實驗室、創新 品牌故事', productSectionStyle: '玻璃感 / 青綠 / 冷色', menuSectionStyle: '科技清單', storeInfoStyle: '飲研實驗室 資訊卡', faqStyle: '飲研實驗室 FAQ', footerStyle: '科技感、透明感、實驗室、創新 footer' },
    productCardSkin: { cardMode: '玻璃感 / 青綠 / 冷色', background: '玻璃感 / 青綠 / 冷色', border: '依 飲研實驗室 palette 客製邊框', priceColor: '依 飲研實驗室 accent 客製', imagePlaceholderStyle: '實驗器皿 / 氣泡抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '科技清單', rowStyle: '依 飲研實驗室 mood 客製 row', priceStyle: '依 飲研實驗室 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '實驗器皿 / 氣泡抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-charcoal-essence',
    templateName: '炭火本味',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-charcoal-essence.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-charcoal-essence.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-charcoal-essence.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '炭黑、火光、職人、烤物', primaryKeywords: ['炭黑', '火光', '職人', '烤物'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得白色商品卡'], requiredLook: ['深色炭火卡', '深色餐牌', '炭火 / 火光抽象'] },
    pageSkin: { background: '炭黑、火光、職人、烤物', texture: '炭火 / 火光抽象', overallMood: '炭黑、火光、職人、烤物' },
    headerSkin: { expectedStyle: '炭黑、火光、職人、烤物 header/nav', background: '必須呼應 炭火本味 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 炭火本味 mood 客製' },
    heroSkin: { artworkUsage: 'full-bleed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '炭黑、火光、職人、烤物 品牌故事', productSectionStyle: '深色炭火卡', menuSectionStyle: '深色餐牌', storeInfoStyle: '炭火本味 資訊卡', faqStyle: '炭火本味 FAQ', footerStyle: '炭黑、火光、職人、烤物 footer' },
    productCardSkin: { cardMode: '深色炭火卡', background: '深色炭火卡', border: '依 炭火本味 palette 客製邊框', priceColor: '依 炭火本味 accent 客製', imagePlaceholderStyle: '炭火 / 火光抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '深色餐牌', rowStyle: '依 炭火本味 mood 客製 row', priceStyle: '依 炭火本味 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '炭火 / 火光抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-rice-kitchen',
    templateName: '米香食堂',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-rice-kitchen.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-rice-kitchen.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-rice-kitchen.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '米白、家常、溫暖、親切', primaryKeywords: ['米白', '家常', '溫暖', '親切'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得冷調色卡'], requiredLook: ['米色 / 紙感卡', '家常食堂清單', '米粒 / 碗盤抽象'] },
    pageSkin: { background: '米白、家常、溫暖、親切', texture: '米粒 / 碗盤抽象', overallMood: '米白、家常、溫暖、親切' },
    headerSkin: { expectedStyle: '米白、家常、溫暖、親切 header/nav', background: '必須呼應 米香食堂 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 米香食堂 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '米白、家常、溫暖、親切 品牌故事', productSectionStyle: '米色 / 紙感卡', menuSectionStyle: '家常食堂清單', storeInfoStyle: '米香食堂 資訊卡', faqStyle: '米香食堂 FAQ', footerStyle: '米白、家常、溫暖、親切 footer' },
    productCardSkin: { cardMode: '米色 / 紙感卡', background: '米色 / 紙感卡', border: '依 米香食堂 palette 客製邊框', priceColor: '依 米香食堂 accent 客製', imagePlaceholderStyle: '米粒 / 碗盤抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '家常食堂清單', rowStyle: '依 米香食堂 mood 客製 row', priceStyle: '依 米香食堂 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '米粒 / 碗盤抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-golden-banquet',
    templateName: '金色晚宴',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-golden-banquet.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-golden-banquet.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-golden-banquet.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '黑金、宴席、高級、精品餐飲', primaryKeywords: ['黑金', '宴席', '高級', '精品餐飲'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡或普通棕色卡'], requiredLook: ['黑底金線卡', '高級菜單', '黑金餐牌'] },
    pageSkin: { background: '黑金、宴席、高級、精品餐飲', texture: '黑金餐牌', overallMood: '黑金、宴席、高級、精品餐飲' },
    headerSkin: { expectedStyle: '黑金、宴席、高級、精品餐飲 header/nav', background: '必須呼應 金色晚宴 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 金色晚宴 mood 客製' },
    heroSkin: { artworkUsage: 'framed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '黑金、宴席、高級、精品餐飲 品牌故事', productSectionStyle: '黑底金線卡', menuSectionStyle: '高級菜單', storeInfoStyle: '金色晚宴 資訊卡', faqStyle: '金色晚宴 FAQ', footerStyle: '黑金、宴席、高級、精品餐飲 footer' },
    productCardSkin: { cardMode: '黑底金線卡', background: '黑底金線卡', border: '依 金色晚宴 palette 客製邊框', priceColor: '依 金色晚宴 accent 客製', imagePlaceholderStyle: '黑金餐牌', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '高級菜單', rowStyle: '依 金色晚宴 mood 客製 row', priceStyle: '依 金色晚宴 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '黑金餐牌', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-corner-meal',
    templateName: '街角食光',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-corner-meal.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-corner-meal.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-corner-meal.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '街角、明亮、日常、親切', primaryKeywords: ['街角', '明亮', '日常', '親切'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得過於高級或深色'], requiredLook: ['生活感白卡 + 柔和照片感', '明亮社區餐館清單', '街角窗景抽象'] },
    pageSkin: { background: '街角、明亮、日常、親切', texture: '街角窗景抽象', overallMood: '街角、明亮、日常、親切' },
    headerSkin: { expectedStyle: '街角、明亮、日常、親切 header/nav', background: '必須呼應 街角食光 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 街角食光 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '街角、明亮、日常、親切 品牌故事', productSectionStyle: '生活感白卡 + 柔和照片感', menuSectionStyle: '明亮社區餐館清單', storeInfoStyle: '街角食光 資訊卡', faqStyle: '街角食光 FAQ', footerStyle: '街角、明亮、日常、親切 footer' },
    productCardSkin: { cardMode: '生活感白卡 + 柔和照片感', background: '生活感白卡 + 柔和照片感', border: '依 街角食光 palette 客製邊框', priceColor: '依 街角食光 accent 客製', imagePlaceholderStyle: '街角窗景抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '明亮社區餐館清單', rowStyle: '依 街角食光 mood 客製 row', priceStyle: '依 街角食光 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '街角窗景抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-spicy-market',
    templateName: '香辣市集',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-spicy-market.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-spicy-market.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-spicy-market.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '紅、橘、熱辣、市集', primaryKeywords: ['紅', '橘', '熱辣', '市集'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡'], requiredLook: ['紅橘熱炒卡', '熱鬧市集菜單', '辣椒 / 火焰抽象'] },
    pageSkin: { background: '紅、橘、熱辣、市集', texture: '辣椒 / 火焰抽象', overallMood: '紅、橘、熱辣、市集' },
    headerSkin: { expectedStyle: '紅、橘、熱辣、市集 header/nav', background: '必須呼應 香辣市集 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 香辣市集 mood 客製' },
    heroSkin: { artworkUsage: 'full-bleed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '紅、橘、熱辣、市集 品牌故事', productSectionStyle: '紅橘熱炒卡', menuSectionStyle: '熱鬧市集菜單', storeInfoStyle: '香辣市集 資訊卡', faqStyle: '香辣市集 FAQ', footerStyle: '紅、橘、熱辣、市集 footer' },
    productCardSkin: { cardMode: '紅橘熱炒卡', background: '紅橘熱炒卡', border: '依 香辣市集 palette 客製邊框', priceColor: '依 香辣市集 accent 客製', imagePlaceholderStyle: '辣椒 / 火焰抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '熱鬧市集菜單', rowStyle: '依 香辣市集 mood 客製 row', priceStyle: '依 香辣市集 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '辣椒 / 火焰抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-sunday-shokudo',
    templateName: '日曜食堂',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-sunday-shokudo.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-sunday-shokudo.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-sunday-shokudo.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '日系、清爽、家庭聚餐、定食感', primaryKeywords: ['日系', '清爽', '家庭聚餐', '定食感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得通用白卡'], requiredLook: ['日式米白卡', '日系定食清單', '碗盤 / 日系線條'] },
    pageSkin: { background: '日系、清爽、家庭聚餐、定食感', texture: '碗盤 / 日系線條', overallMood: '日系、清爽、家庭聚餐、定食感' },
    headerSkin: { expectedStyle: '日系、清爽、家庭聚餐、定食感 header/nav', background: '必須呼應 日曜食堂 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 日曜食堂 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '日系、清爽、家庭聚餐、定食感 品牌故事', productSectionStyle: '日式米白卡', menuSectionStyle: '日系定食清單', storeInfoStyle: '日曜食堂 資訊卡', faqStyle: '日曜食堂 FAQ', footerStyle: '日系、清爽、家庭聚餐、定食感 footer' },
    productCardSkin: { cardMode: '日式米白卡', background: '日式米白卡', border: '依 日曜食堂 palette 客製邊框', priceColor: '依 日曜食堂 accent 客製', imagePlaceholderStyle: '碗盤 / 日系線條', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '日系定食清單', rowStyle: '依 日曜食堂 mood 客製 row', priceStyle: '依 日曜食堂 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '碗盤 / 日系線條', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-kitchen-overture',
    templateName: '廚房序曲',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-kitchen-overture.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-kitchen-overture.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-kitchen-overture.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '主廚、職人、精緻、故事感', primaryKeywords: ['主廚', '職人', '精緻', '故事感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通商品卡'], requiredLook: ['chef editorial card', 'chef tasting menu', '廚房器具 / 餐盤抽象'] },
    pageSkin: { background: '主廚、職人、精緻、故事感', texture: '廚房器具 / 餐盤抽象', overallMood: '主廚、職人、精緻、故事感' },
    headerSkin: { expectedStyle: '主廚、職人、精緻、故事感 header/nav', background: '必須呼應 廚房序曲 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 廚房序曲 mood 客製' },
    heroSkin: { artworkUsage: 'framed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '主廚、職人、精緻、故事感 品牌故事', productSectionStyle: 'chef editorial card', menuSectionStyle: 'chef tasting menu', storeInfoStyle: '廚房序曲 資訊卡', faqStyle: '廚房序曲 FAQ', footerStyle: '主廚、職人、精緻、故事感 footer' },
    productCardSkin: { cardMode: 'chef editorial card', background: 'chef editorial card', border: '依 廚房序曲 palette 客製邊框', priceColor: '依 廚房序曲 accent 客製', imagePlaceholderStyle: '廚房器具 / 餐盤抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'chef tasting menu', rowStyle: '依 廚房序曲 mood 客製 row', priceStyle: '依 廚房序曲 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '廚房器具 / 餐盤抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-brunch-garden',
    templateName: '早午餐花園',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-brunch-garden.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-brunch-garden.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-brunch-garden.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '花園、早午餐、明亮、輕食', primaryKeywords: ['花園', '早午餐', '明亮', '輕食'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得一般餐廳卡'], requiredLook: ['自然綠 / 奶油白卡', 'brunch menu', '花朵 / 葉子抽象'] },
    pageSkin: { background: '花園、早午餐、明亮、輕食', texture: '花朵 / 葉子抽象', overallMood: '花園、早午餐、明亮、輕食' },
    headerSkin: { expectedStyle: '花園、早午餐、明亮、輕食 header/nav', background: '必須呼應 早午餐花園 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 早午餐花園 mood 客製' },
    heroSkin: { artworkUsage: 'poster', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '花園、早午餐、明亮、輕食 品牌故事', productSectionStyle: '自然綠 / 奶油白卡', menuSectionStyle: 'brunch menu', storeInfoStyle: '早午餐花園 資訊卡', faqStyle: '早午餐花園 FAQ', footerStyle: '花園、早午餐、明亮、輕食 footer' },
    productCardSkin: { cardMode: '自然綠 / 奶油白卡', background: '自然綠 / 奶油白卡', border: '依 早午餐花園 palette 客製邊框', priceColor: '依 早午餐花園 accent 客製', imagePlaceholderStyle: '花朵 / 葉子抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'brunch menu', rowStyle: '依 早午餐花園 mood 客製 row', priceStyle: '依 早午餐花園 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '花朵 / 葉子抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-hotpot-home',
    templateName: '鍋物暖居',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-hotpot-home.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-hotpot-home.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-hotpot-home.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '暖色、聚餐、鍋物、家聚', primaryKeywords: ['暖色', '聚餐', '鍋物', '家聚'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得冷白卡'], requiredLook: ['暖紅 / 米色 / 圓潤卡', '鍋物套餐感', '蒸氣 / 圓鍋抽象'] },
    pageSkin: { background: '暖色、聚餐、鍋物、家聚', texture: '蒸氣 / 圓鍋抽象', overallMood: '暖色、聚餐、鍋物、家聚' },
    headerSkin: { expectedStyle: '暖色、聚餐、鍋物、家聚 header/nav', background: '必須呼應 鍋物暖居 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 鍋物暖居 mood 客製' },
    heroSkin: { artworkUsage: 'full-bleed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '暖色、聚餐、鍋物、家聚 品牌故事', productSectionStyle: '暖紅 / 米色 / 圓潤卡', menuSectionStyle: '鍋物套餐感', storeInfoStyle: '鍋物暖居 資訊卡', faqStyle: '鍋物暖居 FAQ', footerStyle: '暖色、聚餐、鍋物、家聚 footer' },
    productCardSkin: { cardMode: '暖紅 / 米色 / 圓潤卡', background: '暖紅 / 米色 / 圓潤卡', border: '依 鍋物暖居 palette 客製邊框', priceColor: '依 鍋物暖居 accent 客製', imagePlaceholderStyle: '蒸氣 / 圓鍋抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '鍋物套餐感', rowStyle: '依 鍋物暖居 mood 客製 row', priceStyle: '依 鍋物暖居 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '蒸氣 / 圓鍋抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'restaurant-fast-enjoy',
    templateName: '食尚快享',
    industry: 'restaurant',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/restaurant/restaurant-fast-enjoy.png', previewHeroSrc: '/template-gallery-ai/restaurant/restaurant-fast-enjoy.png', exportHeroSrc: '/template-gallery-ai/restaurant/restaurant-fast-enjoy.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '快速、外帶、效率、商業感', primaryKeywords: ['快速', '外帶', '效率', '商業感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得高級餐廳感'], requiredLook: ['明亮高轉換卡', '快餐清楚價格', '外帶袋 / 速度線'] },
    pageSkin: { background: '快速、外帶、效率、商業感', texture: '外帶袋 / 速度線', overallMood: '快速、外帶、效率、商業感' },
    headerSkin: { expectedStyle: '快速、外帶、效率、商業感 header/nav', background: '必須呼應 食尚快享 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 食尚快享 mood 客製' },
    heroSkin: { artworkUsage: 'poster', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '快速、外帶、效率、商業感 品牌故事', productSectionStyle: '明亮高轉換卡', menuSectionStyle: '快餐清楚價格', storeInfoStyle: '食尚快享 資訊卡', faqStyle: '食尚快享 FAQ', footerStyle: '快速、外帶、效率、商業感 footer' },
    productCardSkin: { cardMode: '明亮高轉換卡', background: '明亮高轉換卡', border: '依 食尚快享 palette 客製邊框', priceColor: '依 食尚快享 accent 客製', imagePlaceholderStyle: '外帶袋 / 速度線', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '快餐清楚價格', rowStyle: '依 食尚快享 mood 客製 row', priceStyle: '依 食尚快享 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '外帶袋 / 速度線', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-nordic-morning',
    templateName: '北歐晨光',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-nordic-morning.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-nordic-morning.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-nordic-morning.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '北歐、淺木、晨光、留白', primaryKeywords: ['北歐', '淺木', '晨光', '留白'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡'], requiredLook: ['極簡淺木白卡', '北歐清單', '光影 / 木紋抽象'] },
    pageSkin: { background: '北歐、淺木、晨光、留白', texture: '光影 / 木紋抽象', overallMood: '北歐、淺木、晨光、留白' },
    headerSkin: { expectedStyle: '北歐、淺木、晨光、留白 header/nav', background: '必須呼應 北歐晨光 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 北歐晨光 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '北歐、淺木、晨光、留白 品牌故事', productSectionStyle: '極簡淺木白卡', menuSectionStyle: '北歐清單', storeInfoStyle: '北歐晨光 資訊卡', faqStyle: '北歐晨光 FAQ', footerStyle: '北歐、淺木、晨光、留白 footer' },
    productCardSkin: { cardMode: '極簡淺木白卡', background: '極簡淺木白卡', border: '依 北歐晨光 palette 客製邊框', priceColor: '依 北歐晨光 accent 客製', imagePlaceholderStyle: '光影 / 木紋抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '北歐清單', rowStyle: '依 北歐晨光 mood 客製 row', priceStyle: '依 北歐晨光 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '光影 / 木紋抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-midnight-roast',
    templateName: '午夜焙煎',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-midnight-roast.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-midnight-roast.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-midnight-roast.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '深色、咖啡烘焙、夜間、精品', primaryKeywords: ['深色', '咖啡烘焙', '夜間', '精品'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通白卡'], requiredLook: ['深咖啡卡', 'roastery menu', '咖啡豆 / 烘焙光'] },
    pageSkin: { background: '深色、咖啡烘焙、夜間、精品', texture: '咖啡豆 / 烘焙光', overallMood: '深色、咖啡烘焙、夜間、精品' },
    headerSkin: { expectedStyle: '深色、咖啡烘焙、夜間、精品 header/nav', background: '必須呼應 午夜焙煎 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 午夜焙煎 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '深色、咖啡烘焙、夜間、精品 品牌故事', productSectionStyle: '深咖啡卡', menuSectionStyle: 'roastery menu', storeInfoStyle: '午夜焙煎 資訊卡', faqStyle: '午夜焙煎 FAQ', footerStyle: '深色、咖啡烘焙、夜間、精品 footer' },
    productCardSkin: { cardMode: '深咖啡卡', background: '深咖啡卡', border: '依 午夜焙煎 palette 客製邊框', priceColor: '依 午夜焙煎 accent 客製', imagePlaceholderStyle: '咖啡豆 / 烘焙光', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'roastery menu', rowStyle: '依 午夜焙煎 mood 客製 row', priceStyle: '依 午夜焙煎 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '咖啡豆 / 烘焙光', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-cream-library',
    templateName: '奶油書房',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-cream-library.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-cream-library.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-cream-library.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '奶油色、書房、安靜、甜點', primaryKeywords: ['奶油色', '書房', '安靜', '甜點'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得一般咖啡卡'], requiredLook: ['奶油紙感卡', '書房感清單', '書頁 / 咖啡杯抽象'] },
    pageSkin: { background: '奶油色、書房、安靜、甜點', texture: '書頁 / 咖啡杯抽象', overallMood: '奶油色、書房、安靜、甜點' },
    headerSkin: { expectedStyle: '奶油色、書房、安靜、甜點 header/nav', background: '必須呼應 奶油書房 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 奶油書房 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '奶油色、書房、安靜、甜點 品牌故事', productSectionStyle: '奶油紙感卡', menuSectionStyle: '書房感清單', storeInfoStyle: '奶油書房 資訊卡', faqStyle: '奶油書房 FAQ', footerStyle: '奶油色、書房、安靜、甜點 footer' },
    productCardSkin: { cardMode: '奶油紙感卡', background: '奶油紙感卡', border: '依 奶油書房 palette 客製邊框', priceColor: '依 奶油書房 accent 客製', imagePlaceholderStyle: '書頁 / 咖啡杯抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '書房感清單', rowStyle: '依 奶油書房 mood 客製 row', priceStyle: '依 奶油書房 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '書頁 / 咖啡杯抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-forest-teatime',
    templateName: '森林午茶',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-forest-teatime.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-forest-teatime.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-forest-teatime.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '森林綠、下午茶、自然、甜點', primaryKeywords: ['森林綠', '下午茶', '自然', '甜點'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通綠色卡'], requiredLook: ['綠意 / 奶油卡', '午茶甜點清單', '森林 / 葉子'] },
    pageSkin: { background: '森林綠、下午茶、自然、甜點', texture: '森林 / 葉子', overallMood: '森林綠、下午茶、自然、甜點' },
    headerSkin: { expectedStyle: '森林綠、下午茶、自然、甜點 header/nav', background: '必須呼應 森林午茶 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 森林午茶 mood 客製' },
    heroSkin: { artworkUsage: 'split', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '森林綠、下午茶、自然、甜點 品牌故事', productSectionStyle: '綠意 / 奶油卡', menuSectionStyle: '午茶甜點清單', storeInfoStyle: '森林午茶 資訊卡', faqStyle: '森林午茶 FAQ', footerStyle: '森林綠、下午茶、自然、甜點 footer' },
    productCardSkin: { cardMode: '綠意 / 奶油卡', background: '綠意 / 奶油卡', border: '依 森林午茶 palette 客製邊框', priceColor: '依 森林午茶 accent 客製', imagePlaceholderStyle: '森林 / 葉子', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '午茶甜點清單', rowStyle: '依 森林午茶 mood 客製 row', priceStyle: '依 森林午茶 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '森林 / 葉子', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-window-seat',
    templateName: '玻璃窗邊',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-window-seat.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-window-seat.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-window-seat.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '窗邊、光影、質感、內用咖啡', primaryKeywords: ['窗邊', '光影', '質感', '內用咖啡'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得白卡無光影'], requiredLook: ['半透明 glass card', 'light editorial menu', '窗影 / 光線抽象'] },
    pageSkin: { background: '窗邊、光影、質感、內用咖啡', texture: '窗影 / 光線抽象', overallMood: '窗邊、光影、質感、內用咖啡' },
    headerSkin: { expectedStyle: '窗邊、光影、質感、內用咖啡 header/nav', background: '必須呼應 玻璃窗邊 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 玻璃窗邊 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '窗邊、光影、質感、內用咖啡 品牌故事', productSectionStyle: '半透明 glass card', menuSectionStyle: 'light editorial menu', storeInfoStyle: '玻璃窗邊 資訊卡', faqStyle: '玻璃窗邊 FAQ', footerStyle: '窗邊、光影、質感、內用咖啡 footer' },
    productCardSkin: { cardMode: '半透明 glass card', background: '半透明 glass card', border: '依 玻璃窗邊 palette 客製邊框', priceColor: '依 玻璃窗邊 accent 客製', imagePlaceholderStyle: '窗影 / 光線抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'light editorial menu', rowStyle: '依 玻璃窗邊 mood 客製 row', priceStyle: '依 玻璃窗邊 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '窗影 / 光線抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-mocha-studio',
    templateName: '摩卡畫室',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-mocha-studio.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-mocha-studio.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-mocha-studio.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '摩卡、藝術、工作室、手作', primaryKeywords: ['摩卡', '藝術', '工作室', '手作'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通咖啡卡'], requiredLook: ['摩卡棕 / 畫室紙感卡', 'artist cafe menu', '畫筆 / 咖啡杯抽象'] },
    pageSkin: { background: '摩卡、藝術、工作室、手作', texture: '畫筆 / 咖啡杯抽象', overallMood: '摩卡、藝術、工作室、手作' },
    headerSkin: { expectedStyle: '摩卡、藝術、工作室、手作 header/nav', background: '必須呼應 摩卡畫室 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 摩卡畫室 mood 客製' },
    heroSkin: { artworkUsage: 'full-bleed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '摩卡、藝術、工作室、手作 品牌故事', productSectionStyle: '摩卡棕 / 畫室紙感卡', menuSectionStyle: 'artist cafe menu', storeInfoStyle: '摩卡畫室 資訊卡', faqStyle: '摩卡畫室 FAQ', footerStyle: '摩卡、藝術、工作室、手作 footer' },
    productCardSkin: { cardMode: '摩卡棕 / 畫室紙感卡', background: '摩卡棕 / 畫室紙感卡', border: '依 摩卡畫室 palette 客製邊框', priceColor: '依 摩卡畫室 accent 客製', imagePlaceholderStyle: '畫筆 / 咖啡杯抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'artist cafe menu', rowStyle: '依 摩卡畫室 mood 客製 row', priceStyle: '依 摩卡畫室 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '畫筆 / 咖啡杯抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-white-dripper',
    templateName: '白瓷濾杯',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-white-dripper.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-white-dripper.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-white-dripper.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '白瓷、手沖、極簡、精品', primaryKeywords: ['白瓷', '手沖', '極簡', '精品'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得灰色普通卡'], requiredLook: ['白瓷極簡卡，細線', '精品手沖清單', '濾杯 / 圓形細線'] },
    pageSkin: { background: '白瓷、手沖、極簡、精品', texture: '濾杯 / 圓形細線', overallMood: '白瓷、手沖、極簡、精品' },
    headerSkin: { expectedStyle: '白瓷、手沖、極簡、精品 header/nav', background: '必須呼應 白瓷濾杯 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 白瓷濾杯 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '白瓷、手沖、極簡、精品 品牌故事', productSectionStyle: '白瓷極簡卡，細線', menuSectionStyle: '精品手沖清單', storeInfoStyle: '白瓷濾杯 資訊卡', faqStyle: '白瓷濾杯 FAQ', footerStyle: '白瓷、手沖、極簡、精品 footer' },
    productCardSkin: { cardMode: '白瓷極簡卡，細線', background: '白瓷極簡卡，細線', border: '依 白瓷濾杯 palette 客製邊框', priceColor: '依 白瓷濾杯 accent 客製', imagePlaceholderStyle: '濾杯 / 圓形細線', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '精品手沖清單', rowStyle: '依 白瓷濾杯 mood 客製 row', priceStyle: '依 白瓷濾杯 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '濾杯 / 圓形細線', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-caramel-afternoon',
    templateName: '焦糖午後',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-caramel-afternoon.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-caramel-afternoon.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-caramel-afternoon.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '焦糖、午後、甜點、暖色', primaryKeywords: ['焦糖', '午後', '甜點', '暖色'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得一般咖啡色卡'], requiredLook: ['焦糖奶油卡', '甜點咖啡清單', '焦糖圓形 / 奶油色'] },
    pageSkin: { background: '焦糖、午後、甜點、暖色', texture: '焦糖圓形 / 奶油色', overallMood: '焦糖、午後、甜點、暖色' },
    headerSkin: { expectedStyle: '焦糖、午後、甜點、暖色 header/nav', background: '必須呼應 焦糖午後 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 焦糖午後 mood 客製' },
    heroSkin: { artworkUsage: 'full-bleed', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '焦糖、午後、甜點、暖色 品牌故事', productSectionStyle: '焦糖奶油卡', menuSectionStyle: '甜點咖啡清單', storeInfoStyle: '焦糖午後 資訊卡', faqStyle: '焦糖午後 FAQ', footerStyle: '焦糖、午後、甜點、暖色 footer' },
    productCardSkin: { cardMode: '焦糖奶油卡', background: '焦糖奶油卡', border: '依 焦糖午後 palette 客製邊框', priceColor: '依 焦糖午後 accent 客製', imagePlaceholderStyle: '焦糖圓形 / 奶油色', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '甜點咖啡清單', rowStyle: '依 焦糖午後 mood 客製 row', priceStyle: '依 焦糖午後 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '焦糖圓形 / 奶油色', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-urban-monochrome',
    templateName: '城市黑白',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-urban-monochrome.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-urban-monochrome.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-urban-monochrome.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '黑白、都會、時尚、攝影感', primaryKeywords: ['黑白', '都會', '時尚', '攝影感'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得普通灰卡'], requiredLook: ['黑白高對比卡', 'monochrome editorial', '黑白幾何'] },
    pageSkin: { background: '黑白、都會、時尚、攝影感', texture: '黑白幾何', overallMood: '黑白、都會、時尚、攝影感' },
    headerSkin: { expectedStyle: '黑白、都會、時尚、攝影感 header/nav', background: '必須呼應 城市黑白 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 城市黑白 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '黑白、都會、時尚、攝影感 品牌故事', productSectionStyle: '黑白高對比卡', menuSectionStyle: 'monochrome editorial', storeInfoStyle: '城市黑白 資訊卡', faqStyle: '城市黑白 FAQ', footerStyle: '黑白、都會、時尚、攝影感 footer' },
    productCardSkin: { cardMode: '黑白高對比卡', background: '黑白高對比卡', border: '依 城市黑白 palette 客製邊框', priceColor: '依 城市黑白 accent 客製', imagePlaceholderStyle: '黑白幾何', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: 'monochrome editorial', rowStyle: '依 城市黑白 mood 客製 row', priceStyle: '依 城市黑白 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '黑白幾何', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
  {
    templateId: 'cafe-daily-corner',
    templateName: '日常一隅',
    industry: 'cafe',
    sourceArtwork: { gallerySrc: '/template-gallery-ai/cafe/cafe-daily-corner.png', previewHeroSrc: '/template-gallery-ai/cafe/cafe-daily-corner.png', exportHeroSrc: '/template-gallery-ai/cafe/cafe-daily-corner.png', mustUseSameArtwork: true },
    visualIdentity: { mood: '社區、日常、自然光、親切', primaryKeywords: ['社區', '日常', '自然光', '親切'], forbiddenLook: ['通用白卡', '通用色卡', '普通灰色 placeholder', '不得通用咖啡卡'], requiredLook: ['柔和生活感卡', '社區咖啡清單', '日光 / 小角落抽象'] },
    pageSkin: { background: '社區、日常、自然光、親切', texture: '日光 / 小角落抽象', overallMood: '社區、日常、自然光、親切' },
    headerSkin: { expectedStyle: '社區、日常、自然光、親切 header/nav', background: '必須呼應 日常一隅 主視覺', textColor: '高可讀', borderOrShadow: '非 generic，依 日常一隅 mood 客製' },
    heroSkin: { artworkUsage: 'editorial', overlayRequired: true, textPanelRequired: true, headingReadable: true, ctaVisible: true },
    sectionSkin: { brandStoryStyle: '社區、日常、自然光、親切 品牌故事', productSectionStyle: '柔和生活感卡', menuSectionStyle: '社區咖啡清單', storeInfoStyle: '日常一隅 資訊卡', faqStyle: '日常一隅 FAQ', footerStyle: '社區、日常、自然光、親切 footer' },
    productCardSkin: { cardMode: '柔和生活感卡', background: '柔和生活感卡', border: '依 日常一隅 palette 客製邊框', priceColor: '依 日常一隅 accent 客製', imagePlaceholderStyle: '日光 / 小角落抽象', mustNotBeGenericWhiteCard: true },
    menuListSkin: { listMode: '社區咖啡清單', rowStyle: '依 日常一隅 mood 客製 row', priceStyle: '依 日常一隅 accent 客製價格', mustNotBeGenericWhiteList: true },
    placeholderSkin: { placeholderMode: '日光 / 小角落抽象', mustNotShowStoreSiteBuilderText: true, mustMatchTemplateMood: true },
    exportRequirement: { exportMustMatchPreview: true, artworkMustBeInAssets: true, noRemoteDependency: true },
  },
] satisfies TemplateVisualContract[];

export const templateVisualContractMap = Object.fromEntries(templateVisualContracts.map(contract => [contract.templateId, contract])) as Record<string, TemplateVisualContract>;

export function getTemplateVisualContract(templateId?: string): TemplateVisualContract {
  if (!templateId) throw new Error('Template is missing templateId; visual contract is required.');
  const contract = templateVisualContractMap[templateId];
  if (!contract) throw new Error(`此模板尚未完成視覺合約，暫不可套用。 (${templateId})`);
  return contract;
}

export function assertTemplateVisualContractComplete(contract: TemplateVisualContract): true {
  const missing: string[] = [];
  if (!contract.templateId) missing.push('templateId');
  if (!contract.sourceArtwork?.gallerySrc || !contract.sourceArtwork?.previewHeroSrc || !contract.sourceArtwork?.exportHeroSrc) missing.push('sourceArtwork');
  if (!contract.visualIdentity?.mood || !contract.visualIdentity.requiredLook?.length) missing.push('visualIdentity');
  if (!contract.productCardSkin?.mustNotBeGenericWhiteCard) missing.push('productCardSkin');
  if (!contract.menuListSkin?.mustNotBeGenericWhiteList) missing.push('menuListSkin');
  if (!contract.placeholderSkin?.mustMatchTemplateMood || !contract.placeholderSkin.mustNotShowStoreSiteBuilderText) missing.push('placeholderSkin');
  if (!contract.exportRequirement?.exportMustMatchPreview) missing.push('exportRequirement');
  if (missing.length) throw new Error(`此模板尚未完成視覺合約，暫不可套用。 Missing: ${missing.join(', ')}`);
  return true;
}
