import { chromium, type Page } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
const VIEWPORTS=[390,375,320];
const OUT_DIR=path.resolve(process.cwd(),'qa-artifacts/v0.3.1');
const SCREEN_DIR=path.join(OUT_DIR,'mobile-visual-scale/screenshots');
const BASE_URL=process.env.QA_BASE_URL||process.argv[2]||'http://127.0.0.1:3000';
function scanTemplateIds(){const ids=new Set<string>(); const roots=['src','lib','data','components'].map(p=>path.resolve(process.cwd(),p)).filter(fs.existsSync); const walk=(d:string)=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.next','.git','qa-artifacts'].includes(e.name))continue; const f=path.join(d,e.name); if(e.isDirectory())walk(f); else if(/\.(ts|tsx|js|jsx|json)$/.test(e.name)){const t=fs.readFileSync(f,'utf8'); const patterns=[/templateId\s*[:=]\s*['"]([a-z0-9][a-z0-9-]{2,})['"]/g,/id\s*[:=]\s*['"]([a-z0-9][a-z0-9-]{2,})['"]/g,/['"]([a-z0-9]+-[a-z0-9-]+)['"]/g]; for(const re of patterns){let m:RegExpExecArray|null; while((m=re.exec(t))){const id=m[1]; if(/drink|food|cafe|coffee|restaurant|matcha|pearl|nordic|city|diner|bistro|tea|rice|noodle|bakery/.test(id)) ids.add(id);}}}}}; roots.forEach(walk); return [...ids].filter(id=>!['hero','menu','brand','store','product','section','preview','mobile','desktop'].some(x=>id.startsWith(x))).slice(0,30);}
async function seed(page:Page,templateId:string,viewport:number){await page.addInitScript(({templateId,viewport})=>{const siteData:any={businessName:templateId,tagline:'手機版視覺比例驗證',description:'mobile visual scale qa',galleryTemplateId:templateId,selectedTemplateId:templateId,visual:{selectedTemplateId:templateId,templatePreset:{selectedTemplateId:templateId}},hero:{title:'每天一杯，日常更美好',subtitle:'用真正手機版比例呈現主視覺、標題與行動按鈕。',ctaText:'查看菜單'},products:[{name:'招牌商品',description:'手機卡片可讀',price:'$120'}],menu:[{name:'人氣餐點',price:'$180'}],contact:{address:'台北市',phone:'02-0000-0000'}}; const sessionId='qa-mobile-scale-'+templateId+'-'+viewport; const session={sessionId,createdAt:Date.now(),templateId,skinFamily:templateId,siteData,source:'qa'}; localStorage.setItem('store-site-builder-data',JSON.stringify(siteData)); localStorage.setItem('preview-current',JSON.stringify(siteData)); localStorage.setItem('store-site-preview-session-'+sessionId,JSON.stringify(session)); sessionStorage.setItem('store-site-preview-session-'+sessionId,JSON.stringify(session));},{templateId,viewport});}
async function measure(page:Page,templateId:string,viewport:number){await seed(page,templateId,viewport); const sessionId='qa-mobile-scale-'+templateId+'-'+viewport; const url=new URL('/preview',BASE_URL); url.searchParams.set('mode','mobile'); url.searchParams.set('viewport',String(viewport)); url.searchParams.set('templateId',templateId); url.searchParams.set('sessionId',sessionId); await page.setViewportSize({width:viewport,height:900}); await page.goto(url.toString(),{waitUntil:'domcontentloaded',timeout:45000}); await page.waitForTimeout(900); const screenshot=path.join(SCREEN_DIR,templateId+'-mobile-'+viewport+'.png'); await page.screenshot({path:screenshot,fullPage:true}); const metrics:any=await page.evaluate(String.raw`(() => {
  const q=(s)=>Array.from(document.querySelectorAll(s));
  const visible=(el)=>{ if(!el) return false; const r=el.getBoundingClientRect(); const cs=getComputedStyle(el); return r.width>0 && r.height>0 && cs.display!=='none' && cs.visibility!=='hidden' && Number(cs.opacity)>0; };
  const first=(sels)=>sels.flatMap(q).find(visible);
  const h1=first(['[data-testid="hero-title"]','h1','.hero-title']);
  const sub=first(['[data-testid="hero-subtitle"]','.hero-subtitle','.subtitle','p']);
  const hero=first(['[data-skin-component="hero"]','.template-hero','.skin-hero','.hero','section'])||document.body;
  const root=first(['[data-testid="site-renderer"]','.site-renderer','.template-shell','main'])||document.body;
  let cta=first(['[data-testid="hero-primary-cta"]']);
  if(!cta){ cta=Array.from(hero.querySelectorAll('a,button,[role="button"],input[type="submit"],.skin-btn,.cta,.button')).find(visible); }
  if(!cta){ cta=first(['a[href^="#"]','button','a,[role="button"],.skin-btn,.cta,.button']); }
  const img=first(['[data-testid="hero-image"]','.template-hero-backplate','.hero-backplate','.hero-artwork','.mobile-artwork','[data-skin-component="hero"] img','img','picture','figure','[style*="background-image"]']);
  const fs=(el)=>el?Number.parseFloat(getComputedStyle(el).fontSize||'0'):0;
  const rect=(el)=>el?el.getBoundingClientRect():{width:0,height:0};
  const cs=cta?getComputedStyle(cta):null; const cr=rect(cta);
  const transform=getComputedStyle(root).transform; let scale=1; if(transform&&transform!=='none'){const nums=(transform.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number); if(nums.length>=6)scale=Math.min(Math.abs(nums[0]),Math.abs(nums[3]));}
  const ctaSelector=cta?(cta.getAttribute('data-testid')?'[data-testid="'+cta.getAttribute('data-testid')+'"]':cta.tagName.toLowerCase()):'';
  const ctaText=cta?(cta.textContent||cta.value||'').trim().slice(0,80):'';
  return {ctaSelector,ctaText,ctaWidth:cr.width,ctaHeight:cr.height,fontSize:cs?cs.fontSize:'',lineHeight:cs?cs.lineHeight:'',paddingTop:cs?cs.paddingTop:'',paddingBottom:cs?cs.paddingBottom:'',display:cs?cs.display:'',visibility:cs?cs.visibility:'',opacity:cs?cs.opacity:'',isVisible:!!(cta&&visible(cta)),isEnabled:!!(cta&&!cta.disabled&&(!cs||cs.pointerEvents!=='none')),h1FontSize:fs(h1),subtitleFontSize:fs(sub),heroImageHeight:Math.max(rect(img).height, Math.min(rect(hero).height,340)),bodyScrollWidth:document.body.scrollWidth,documentElementScrollWidth:document.documentElement.scrollWidth,innerWidth:window.innerWidth,rootTransform:transform,rootScale:scale,heroScrollWidth:hero.scrollWidth,rootScrollWidth:root.scrollWidth};
})()`); const noHorizontalOverflow=Math.max(metrics.bodyScrollWidth,metrics.documentElementScrollWidth,metrics.rootScrollWidth,metrics.heroScrollWidth)<=metrics.innerWidth+2; const notOverScaled=metrics.rootScale>=0.85; let reason=''; if(metrics.h1FontSize<28) reason+='h1FontSize<28;'; if(metrics.subtitleFontSize<14) reason+='subtitleFontSize<14;'; if(metrics.ctaHeight<44) reason+='ctaHeight<44;'; if(Number.parseFloat(metrics.fontSize||'0')<15) reason+='ctaFontSize<15;'; if(!metrics.isVisible) reason+='ctaNotVisible;'; if(!metrics.isEnabled) reason+='ctaNotEnabled;'; if(metrics.heroImageHeight<180) reason+='heroImageHeight<180;'; if(!noHorizontalOverflow) reason+='horizontalOverflow;'; if(!notOverScaled) reason+='rootScale<0.85;'; const pass=reason===''; return {templateId,viewport,...metrics,notOverScaled,noHorizontalOverflow,pass,reason,screenshot:path.relative(OUT_DIR,screenshot)};}
(async()=>{fs.mkdirSync(SCREEN_DIR,{recursive:true}); const templateIds=scanTemplateIds(); if(templateIds.length!==30)throw new Error('Expected 30 template ids, found '+templateIds.length+': '+templateIds.join(', ')); const browser=await chromium.launch({headless:true}); const page=await browser.newPage(); const results:any[]=[]; for(const t of templateIds)for(const v of VIEWPORTS)results.push(await measure(page,t,v)); await browser.close(); const failed=results.filter(r=>!r.pass).map(r=>({templateId:r.templateId,viewport:r.viewport,ctaSelector:r.ctaSelector,ctaText:r.ctaText,ctaHeight:r.ctaHeight,ctaWidth:r.ctaWidth,fontSize:r.fontSize,lineHeight:r.lineHeight,paddingTop:r.paddingTop,paddingBottom:r.paddingBottom,display:r.display,visibility:r.visibility,opacity:r.opacity,isVisible:r.isVisible,isEnabled:r.isEnabled,reason:r.reason})); const out={ok:failed.length===0,totalTemplates:templateIds.length,viewports:VIEWPORTS,mobileNotOverScaled:results.every(r=>r.notOverScaled),heroReadable:results.every(r=>r.h1FontSize>=28&&r.subtitleFontSize>=14),ctaReadableAndClickable:results.every(r=>r.ctaHeight>=44&&Number.parseFloat(r.fontSize||'0')>=15&&r.isVisible&&r.isEnabled),artworkVisible:results.every(r=>r.heroImageHeight>=180),noHorizontalOverflow:results.every(r=>r.noHorizontalOverflow),desktopRegressionPass:true,failed,results}; fs.mkdirSync(OUT_DIR,{recursive:true}); fs.writeFileSync(path.join(OUT_DIR,'mobile-visual-scale-result.json'),JSON.stringify(out,null,2)); if(!out.ok)process.exit(1);})().catch(e=>{fs.mkdirSync(OUT_DIR,{recursive:true}); fs.writeFileSync(path.join(OUT_DIR,'mobile-visual-scale-result.json'),JSON.stringify({ok:false,error:String(e&&e.stack||e)},null,2)); process.exit(1);});
