import { mkdirSync, writeFileSync } from 'fs';
import path from 'path';
import JSZip from 'jszip';
import { chromium } from 'playwright';

const baseUrl = process.env.QA_BASE_URL || 'http://127.0.0.1:3104';
const outDir = process.env.QA_OUT_DIR || '/mnt/d/HERMES_TMP/01_REPO_CLONES/store-site-builder/qa-artifacts/template-gallery-v0.2.0';
mkdirSync(outDir, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1040 }, acceptDownloads: true });
  const consoleErrors: string[] = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await page.goto(`${baseUrl}/builder`, { waitUntil: 'networkidle' });
  await page.evaluate(() => localStorage.clear());
  await page.reload({ waitUntil: 'networkidle' });
  await page.locator('[data-sidebar-button="template"]').click({ force: true });
  await page.screenshot({ path: path.join(outDir, '01-template-gallery-desktop.png'), fullPage: true });
  const drinkCount = await page.locator('[data-testid="template-gallery-grid"] article').count();
  await page.getByRole('tab', { name: /餐飲店/ }).click();
  await page.screenshot({ path: path.join(outDir, '03-restaurant-gallery.png'), fullPage: true });
  const restaurantCount = await page.locator('[data-testid="template-gallery-grid"] article').count();
  await page.getByRole('tab', { name: /咖啡廳/ }).click();
  await page.screenshot({ path: path.join(outDir, '04-cafe-gallery.png'), fullPage: true });
  const cafeCount = await page.locator('[data-testid="template-gallery-grid"] article').count();
  await page.getByRole('tab', { name: /飲料店/ }).click();
  await page.screenshot({ path: path.join(outDir, '02-drink-gallery.png'), fullPage: true });
  await page.getByLabel('搜尋模板').fill('抹茶');
  const searchCount = await page.locator('[data-testid="template-gallery-grid"] article').count();
  await page.getByLabel('搜尋模板').fill('');
  await page.getByRole('button', { name: '高質感' }).click();
  const filteredCount = await page.locator('[data-testid="template-gallery-grid"] article').count();
  await page.getByRole('button', { name: '全部風格' }).click();
  await page.getByLabel('排序').selectOption('popular');
  await page.locator('[data-testid="template-gallery-grid"]').getByRole('button', { name: /快速預覽 抹茶日和/ }).click();
  await page.screenshot({ path: path.join(outDir, '05-preview-modal.png'), fullPage: true });
  await page.getByRole('button', { name: /套用此模板|重新套用此模板/ }).click();
  await page.waitForTimeout(500);
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('store-site-builder-data') || '{}'));
  const applied = stored?.galleryTemplateId === 'drink-matcha-hiyori' && stored?.template === 'fresh-japanese';
  const previewText = await page.locator('[data-testid="preview-panel"]').innerText();
  await page.screenshot({ path: path.join(outDir, '06-applied-builder-preview.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 900 });
  await page.screenshot({ path: path.join(outDir, '07-template-gallery-mobile-390.png'), fullPage: true });
  const mobileOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  await page.setViewportSize({ width: 1440, height: 1040 });
  await page.locator('[data-sidebar-button="export"]').click({ force: true });
  const dl = page.waitForEvent('download');
  await page.getByRole('button', { name: /下載 generated-site\.zip/ }).click();
  const download = await dl;
  const zipPath = path.join(outDir, 'generated-site-gallery-qa.zip');
  await download.saveAs(zipPath);
  const stream = await download.createReadStream();
  if (!stream) throw new Error('download stream unavailable');
  const buffer = await new Promise<Buffer>((resolve, reject) => { const chunks: Buffer[] = []; stream.on('data', c => chunks.push(c)); stream.on('end', () => resolve(Buffer.concat(chunks))); stream.on('error', reject); });
  const zip = await JSZip.loadAsync(buffer);
  const zipFiles = Object.keys(zip.files).filter(n => !zip.files[n].dir).sort();
  const html = await zip.file('index.html')?.async('string') || '';
  const forbidden = /localhost|127\.0\.0\.1|\/_next|_next\//.test(html);
  await browser.close();
  const result = { ok: true, drinkCount, restaurantCount, cafeCount, searchCount, filteredCount, applied, previewSync: /清新日系|日沐茶飲/.test(previewText), mobileOverflow, consoleErrors, zipFiles, forbidden };
  if (drinkCount !== 10 || restaurantCount !== 10 || cafeCount !== 10) throw new Error(`industry count failed ${JSON.stringify(result)}`);
  if (!searchCount || filteredCount >= 10) throw new Error(`search/filter failed ${JSON.stringify(result)}`);
  if (!applied || result.mobileOverflow || consoleErrors.length || forbidden) throw new Error(`regression failed ${JSON.stringify(result)}`);
  writeFileSync(path.join(outDir, 'qa-gallery-result.json'), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
})();
