import type { MediaAsset, SiteData } from '@/types/site';
import { Badge, Button, Card, EmptyState, SectionHeader, Select } from '@/components/ui';
import { validateImage } from '@/lib/validators';

export function MediaManager({ data, onChange }: { data: SiteData; onChange: (d: SiteData) => void }) {
  const upload = (files: FileList | null) => { [...(files || [])].forEach(file => { const err = validateImage(file); if (err) { alert(err); return; } const reader = new FileReader(); reader.onload = () => { const media: MediaAsset = { id: `img-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, name: file.name, type: 'other', mimeType: file.type, dataUrl: String(reader.result) }; onChange({ ...data, media: [...data.media, media], hero: { ...data.hero, imageId: data.hero.imageId || media.id } }); }; reader.readAsDataURL(file); }); };
  const updateType = (id: string, type: MediaAsset['type']) => onChange({ ...data, media: data.media.map(m => m.id === id ? { ...m, type } : m) });
  const remove = (id: string) => onChange({ ...data, hero: { ...data.hero, imageId: data.hero.imageId === id ? undefined : data.hero.imageId }, seo: { ...data.seo, ogImageId: data.seo.ogImageId === id ? undefined : data.seo.ogImageId }, media: data.media.filter(m => m.id !== id) });
  return <Card><SectionHeader eyebrow="Media" title="圖片媒體" description="支援 JPG / PNG / WebP。沒有圖片時模板會使用設計感 CSS placeholder。" /><label className="block cursor-pointer rounded-[28px] border-2 border-dashed border-teal-200 bg-teal-50/60 p-8 text-center transition hover:bg-teal-50"><input type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={e => upload(e.target.files)} /><div className="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-3xl bg-white text-2xl shadow-sm">🖼️</div><b className="text-slate-800">拖曳或點擊上傳圖片</b><p className="mt-1 text-sm text-slate-500">建議上傳 Hero、商品或門市照片。</p></label><div className="mt-5 grid gap-3">{data.media.length === 0 ? <EmptyState title="尚未上傳圖片" description="模板會先使用漂亮的漸層與幾何 placeholder。" icon="🌿" /> : data.media.map(m => <div key={m.id} className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-[80px_1fr_auto]"><img src={m.dataUrl} className="h-20 w-20 rounded-2xl object-cover" alt={m.name} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="truncate text-slate-800">{m.name}</b>{data.hero.imageId === m.id && <Badge>Hero</Badge>}</div><Select label="圖片用途" value={m.type} onChange={e => updateType(m.id, e.target.value as MediaAsset['type'])}><option value="logo">Logo</option><option value="hero">Hero</option><option value="product">商品</option><option value="store">門市</option><option value="other">其他</option></Select></div><Button variant="danger" onClick={() => remove(m.id)}>刪除</Button></div>)}</div></Card>;
}
