import type { SiteData, MenuItem } from '@/types/site';
import { imageSrc } from '@/lib/imageUtils';

const linkLabels: Record<string, string> = { line: 'LINE', instagram: 'Instagram', facebook: 'Facebook', threads: 'Threads', tiktok: 'TikTok', googleMap: 'Google Maps', ubereats: 'Uber Eats', foodpanda: 'foodpanda', orderForm: '立即訂購', reservation: '線上訂位' };
const density = { compact: 'gap-5 py-8', comfortable: 'gap-8 py-12', spacious: 'gap-12 py-16' };
const font = (data: SiteData) => data.theme.fontFamily === 'serif' ? 'Georgia, "Noto Serif TC", serif' : data.theme.fontFamily === 'rounded' ? 'ui-rounded, "Noto Sans TC", system-ui, sans-serif' : 'system-ui, "Noto Sans TC", sans-serif';
const radius = (data: SiteData, min = 12, max = 36) => Math.max(min, Math.min(max, data.theme.sectionRadius));
const btnRadius = (data: SiteData) => data.theme.buttonStyle === 'square' ? 8 : data.theme.buttonStyle === 'rounded' ? 16 : 999;
function Links({ data, className = '' }: { data: SiteData; className?: string }) { const links = Object.entries(data.links).filter(([, v]) => v); return links.length ? <div className={`flex flex-wrap gap-2 ${className}`}>{links.map(([k, v]) => <a key={k} href={v} target="_blank" rel="noopener noreferrer" className="px-4 py-2 text-sm font-black text-white shadow-sm transition hover:scale-105" style={{ background: data.theme.primaryColor, borderRadius: btnRadius(data) }}>{linkLabels[k] || k}</a>)}</div> : null; }
function ProductImage({ data, item, className = '' }: { data: SiteData; item?: MenuItem; className?: string }) { return <img className={`w-full object-cover ${className}`} src={imageSrc(data, item?.imageId)} alt={item?.name || data.store.name} />; }
function StoreInfo({ data, title = '門市資訊' }: { data: SiteData; title?: string }) { return data.modules.storeInfo ? <section className="template-card"><h2>{title}</h2><div className="info-grid"><p>📍 {data.store.address}</p><p>☎ {data.store.phone}</p><p>✉ {data.store.email}</p><p>🕘 {data.store.businessHours}</p></div></section> : null; }
function FAQ({ data }: { data: SiteData }) { return data.modules.faq ? <section><h2 className="section-title">FAQ</h2><div className="faq-list">{data.faq.map(f => <details key={f.question} className="template-card"><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></section> : null; }
function MenuList({ data, title = '菜單總覽' }: { data: SiteData; title?: string }) { return data.modules.menu ? <section><h2 className="section-title">{title}</h2><div className="menu-stack">{data.menu.categories.map(c => <article key={c.id} className="template-card"><h3>{c.name}</h3>{c.description && <p className="muted">{c.description}</p>}<div>{c.items.map(i => <div key={i.id} className="menu-row"><span><b>{i.name}</b><small>{i.description}</small></span><strong>${i.price}</strong></div>)}</div></article>)}</div></section> : null; }
function Footer({ data }: { data: SiteData }) { return data.modules.footer ? <footer>© {new Date().getFullYear()} {data.store.name}</footer> : null; }
function TemplateCSS({ data, mode }: { data: SiteData; mode: 'fresh' | 'premium' | 'playful' }) { const r = mode === 'premium' ? radius(data, 4, 18) : mode === 'playful' ? radius(data, 24, 48) : radius(data, 14, 34); return <style>{`
.store-template{font-family:${font(data)};color:${data.theme.textColor};min-height:100%;overflow:hidden}.store-template a{text-decoration:none}.store-template .wrap{max-width:${mode==='premium'?'1120px':'1040px'};margin:0 auto;padding:20px}.store-template .template-card{border-radius:${r}px;background:rgba(255,255,255,.88);padding:22px;box-shadow:0 18px 45px rgba(15,23,42,.10);border:1px solid rgba(226,232,240,.8)}.store-template h1{font-size:clamp(40px,7vw,76px);line-height:.95;margin:0;letter-spacing:-.045em}.store-template h2,.store-template .section-title{font-size:clamp(26px,3vw,40px);font-weight:900;margin:0 0 18px}.store-template h3{font-size:20px;margin:0 0 8px}.store-template .muted{opacity:.72;line-height:1.75}.store-template .product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.store-template .menu-stack{display:grid;gap:16px}.store-template .menu-row{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-top:1px solid rgba(148,163,184,.22)}.store-template .menu-row small{display:block;margin-top:4px;opacity:.65}.store-template .info-grid{display:grid;gap:8px}.store-template footer{text-align:center;padding:38px 0;opacity:.65}.store-template .faq-list{display:grid;gap:12px}.store-template summary{cursor:pointer;font-weight:900}.store-template .btn-band{border-radius:${r}px;padding:24px;background:${data.theme.primaryColor};color:white}.store-template .placeholder-badge{display:inline-flex;border-radius:999px;padding:8px 14px;background:white;color:${data.theme.primaryColor};font-weight:900}@media(max-width:720px){.store-template .wrap{padding:14px}.store-template .product-grid{grid-template-columns:1fr}.store-template .hero-grid{grid-template-columns:1fr!important}.store-template h1{font-size:42px}.store-template .template-card{padding:16px}.store-template img{max-width:100%}}
`}</style>; }

export function PlayfulColorfulTemplate({ data }: { data: SiteData }) { const featured = data.menu.categories.flatMap(c => c.items).filter(i => i.featured); return <main className="store-template" style={{ background: `linear-gradient(135deg, ${data.theme.backgroundColor}, ${data.theme.secondaryColor})` }}><TemplateCSS data={data} mode="playful" /><div className={`wrap grid ${density[data.theme.layoutDensity]}`}><header className="template-card flex flex-wrap items-center justify-between gap-3"><b className="text-2xl">✨ {data.store.name}</b><span className="rounded-full px-4 py-2 text-sm font-black text-white" style={{ background: data.theme.primaryColor }}>New!</span></header>{data.modules.hero && <section className="hero-grid grid items-center gap-6 md:grid-cols-[1fr_.9fr]"><div className="template-card" style={{ background: 'rgba(255,255,255,.94)' }}><span className="placeholder-badge">本週人氣推薦</span><h1 className="mt-5">{data.hero.title}</h1><p className="muted mt-5 text-lg">{data.hero.subtitle}</p><Links data={data} className="mt-6" /></div><div className="relative"><ProductImage data={data} className="h-80 rotate-1 rounded-[42px] shadow-2xl" /><div className="absolute -right-2 -top-4 rounded-full bg-yellow-300 px-5 py-4 text-xl font-black shadow-lg">HOT</div></div></section>}{data.modules.featuredProducts && <section><h2 className="section-title">人氣商品</h2><div className="product-grid">{featured.map(item => <article key={item.id} className="template-card transition hover:-translate-y-1"><ProductImage data={data} item={item} className="h-36 rounded-[30px]" /><h3 className="mt-4">{item.name}</h3><p className="muted text-sm">{item.description}</p><strong style={{ color: data.theme.primaryColor }}>${item.price}</strong></article>)}</div></section>}<MenuList data={data} />{data.modules.socialLinks && <section className="btn-band"><h2>優惠 / 社群導流</h2><p>追蹤社群、加入 LINE 或直接下單，把人氣商品帶回家。</p><Links data={data} /></section>}<StoreInfo data={data} title="分店資訊" /><FAQ data={data} /><Footer data={data} /></div></main>; }
