import type { SiteData, MenuItem } from '@/types/site';
import { imageSrc } from '@/lib/imageUtils';
import { getTemplateVisualStyle } from '@/lib/templateVisualStyle';

const linkLabels: Record<string, string> = { line: 'LINE', instagram: 'Instagram', facebook: 'Facebook', threads: 'Threads', tiktok: 'TikTok', googleMap: 'Google Maps', ubereats: 'Uber Eats', foodpanda: 'foodpanda', orderForm: '立即訂購', reservation: '線上訂位' };
const density = { compact: 'gap-5 py-8', comfortable: 'gap-8 py-12', spacious: 'gap-12 py-16' };
const font = (data: SiteData) => data.theme.fontFamily === 'serif' ? 'Georgia, "Noto Serif TC", serif' : data.theme.fontFamily === 'rounded' ? 'ui-rounded, "Noto Sans TC", system-ui, sans-serif' : 'system-ui, "Noto Sans TC", sans-serif';
const radius = (data: SiteData, min = 12, max = 36) => Math.max(min, Math.min(max, data.theme.sectionRadius));
const btnRadius = (data: SiteData) => data.theme.buttonStyle === 'square' ? 8 : data.theme.buttonStyle === 'rounded' ? 16 : 999;
function Links({ data, className = '' }: { data: SiteData; className?: string }) { const links = Object.entries(data.links).filter(([, v]) => v); return links.length ? <div className={`flex flex-wrap gap-2 ${className}`}>{links.map(([k, v]) => <a key={k} href={v} target="_blank" rel="noopener noreferrer" className="px-4 py-2 text-sm font-black text-white shadow-sm transition hover:scale-105" style={{ background: data.theme.primaryColor, borderRadius: btnRadius(data) }}>{linkLabels[k] || k}</a>)}</div> : null; }
function ProductImage({ data, item, className = '' }: { data: SiteData; item?: MenuItem; className?: string }) { return <img className={`w-full object-cover ${className}`} src={imageSrc(data, item ? item.imageId : data.hero.imageId)} alt={item?.name || data.store.name} />; }
function StoreInfo({ data, title = '門市資訊' }: { data: SiteData; title?: string }) { return data.modules.storeInfo ? <section className="template-card"><h2>{title}</h2><div className="info-grid"><p>📍 {data.store.address}</p><p>☎ {data.store.phone}</p><p>✉ {data.store.email}</p><p>🕘 {data.store.businessHours}</p></div></section> : null; }
function FAQ({ data }: { data: SiteData }) { return data.modules.faq ? <section><h2 className="section-title">FAQ</h2><div className="faq-list">{data.faq.map(f => <details key={f.question} className="template-card"><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></section> : null; }
function MenuList({ data, title = '菜單總覽' }: { data: SiteData; title?: string }) { return data.modules.menu ? <section><h2 className="section-title">{title}</h2><div className="menu-stack">{data.menu.categories.map(c => <article key={c.id} className="template-card"><h3>{c.name}</h3>{c.description && <p className="muted">{c.description}</p>}<div>{c.items.map(i => <div key={i.id} className="menu-row"><span><b>{i.name}</b><small>{i.description}</small></span><strong>${i.price}</strong></div>)}</div></article>)}</div></section> : null; }
function Footer({ data }: { data: SiteData }) { return data.modules.footer ? <footer>© {new Date().getFullYear()} {data.store.name}</footer> : null; }
function TemplateCSS({ data, mode }: { data: SiteData; mode: 'fresh' | 'premium' | 'playful' }) { const visual = getTemplateVisualStyle(data); const r = visual.radius || (mode === 'premium' ? radius(data, 4, 18) : mode === 'playful' ? radius(data, 24, 48) : radius(data, 14, 34)); const cardBg = visual.cardBackground || 'rgba(255,255,255,.88)'; const cardBorder = visual.cardBorder || 'rgba(226,232,240,.8)'; const cardShadow = visual.cardShadow || '0 18px 45px rgba(15,23,42,.10)'; const heroBg = visual.heroBackgroundStyle || `linear-gradient(135deg, ${data.theme.backgroundColor}, ${data.theme.secondaryColor}33)`; const sectionBg = visual.sectionBackgroundStyle || cardBg; const headingScale = visual.headingScale || 1; return <style>{`
.store-template{font-family:${font(data)};color:${data.theme.textColor};min-height:100%;overflow:hidden;background:${visual.pageBackgroundStyle}}.store-template a{text-decoration:none}.store-template .wrap{max-width:${mode==='premium'?'1120px':'1040px'};margin:0 auto;padding:20px}.store-template .template-card{border-radius:${r}px;background:${cardBg};padding:22px;box-shadow:${cardShadow};border:1px solid ${cardBorder}}.store-template h1{font-size:calc(clamp(40px,7vw,76px) * ${headingScale});line-height:.95;margin:0;letter-spacing:-.045em}.store-template h2,.store-template .section-title{font-size:calc(clamp(26px,3vw,40px) * ${headingScale});font-weight:900;margin:0 0 18px}.store-template h3{font-size:20px;margin:0 0 8px}.store-template .muted{opacity:.72;line-height:1.75}.store-template .product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.store-template .menu-stack{display:grid;gap:16px}.store-template .menu-row{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-top:1px solid rgba(148,163,184,.22)}.store-template .menu-row small{display:block;margin-top:4px;opacity:.65}.store-template .info-grid{display:grid;gap:8px}.store-template footer{text-align:center;padding:38px 0;opacity:.65}.store-template .faq-list{display:grid;gap:12px}.store-template summary{cursor:pointer;font-weight:900}.store-template .btn-band{border-radius:${r}px;padding:24px;${visual.buttonCss};color:${visual.textContrastMode==='light-on-dark'?'#fff':'inherit'}}.store-template .placeholder-badge{display:inline-flex;border-radius:999px;padding:8px 14px;background:${sectionBg};color:${data.theme.primaryColor};font-weight:900;border:1px solid ${cardBorder}}.store-template header.template-card{${visual.navCss}}.store-template .hero-grid{border-radius:${r}px;background:${heroBg}}@media(max-width:720px){.store-template .wrap{padding:14px}.store-template .product-grid{grid-template-columns:1fr}.store-template .hero-grid{grid-template-columns:1fr!important}.store-template h1{font-size:calc(42px * ${headingScale})}.store-template .template-card{padding:16px}.store-template img{max-width:100%}}
`}</style>; }

export function PremiumMinimalTemplate({ data }: { data: SiteData }) { const visual = getTemplateVisualStyle(data); const featured = data.menu.categories.flatMap(c => c.items).filter(i => i.featured); return <main className="store-template" style={{ background: visual.pageBackgroundStyle }}><TemplateCSS data={data} mode="premium" /><div className={`wrap grid ${density[data.theme.layoutDensity]}`}><header className="flex items-center justify-between bg-stone-950 px-6 py-5 text-white"><b className="text-xl tracking-wide">{data.store.name}</b><span className="text-sm uppercase tracking-[0.3em] text-stone-300">Reserve / Takeout</span></header>{data.modules.hero && <section className="hero-grid grid overflow-hidden border border-stone-300 bg-[#fffaf0] md:grid-cols-[.9fr_1.1fr]"><div className="p-7 md:p-12"><p className="mb-5 text-sm font-black uppercase tracking-[0.3em]" style={{ color: data.theme.primaryColor }}>{data.store.tagline}</p><h1>{data.hero.title}</h1><p className="muted mt-6 text-lg">{data.hero.subtitle}</p><Links data={data} className="mt-8" /></div><ProductImage data={data} className="h-full min-h-80" /></section>}{data.modules.featuredProducts && <section><h2 className="section-title">招牌餐點</h2><div className="grid gap-4">{featured.map(item => <article key={item.id} className="template-card grid gap-5 md:grid-cols-[180px_1fr_auto] md:items-center"><ProductImage data={data} item={item} className="h-36 rounded-xl" /><div><h3>{item.name}</h3><p className="muted">{item.description}</p></div><strong style={{ color: data.theme.primaryColor }}>${item.price}</strong></article>)}</div></section>}<MenuList data={data} title="菜單列表" />{data.modules.socialLinks && <section className="btn-band"><h2>訂位 / 外帶</h2><p>選擇外送、訂購表單或訂位連結，快速完成下一步。</p><Links data={data} /></section>}{data.modules.brandStory && <section className="template-card"><h2>關於我們</h2><p className="muted">{data.store.description}</p></section>}<StoreInfo data={data} /><FAQ data={data} /><Footer data={data} /></div></main>; }
